### ISSUE TITLE
multiple build failures

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/z3c.baseregistry#5]
https://travis-ci.org/github/zopefoundation/z3c.baseregistry/builds/443704214

Python 3.4 can be dropped, but I do not see an easy solution for the pypy error
RuntimeError: You are linking against OpenSSL 1.0.1, which is no longer supported by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.

**Comment by jamadden** [comment]
This job is using a very old version of PyPy, while presumably the rest of the image has moved on:
```
Python 2.7.13 (c925e7381036, Jun 05 2017, 21:20:51)
[PyPy 5.8.0 with GCC 6.2.0 20160901]
```

The current version Travis has [is pretty recent](https://travis-ci.org/github/NextThought/nti.schema/jobs/684238198#L223):
```
Python 2.7.13 (8cdda8b8cdb8, Apr 14 2019, 14:06:44)
[PyPy 7.1.1 with GCC 6.2.0 20160901]
```

Dunno why that is. Maybe `group: travis_latest` is needed at the top level? I also cleared the build cache and restarted the job just in case.

**Comment by jamadden** [comment]
A [fresh build on master](https://travis-ci.org/github/zopefoundation/z3c.baseregistry/jobs/686951711) works. It looks like the old build of the 2.0.0 release was using the image that was current at the time, trusty. A new build used the newer image (xenial) with the newer pypy.

**Comment by jugmac00** [comment]
Thanks a lot - I am taking care of the other failure!

**Comment by jugmac00** [comment]
Fixed by #6

**Comment by mgedmin** [comment]
Do we have cron builds enabled for this repo?  (Ideally we'd run a script and enable them for all repos that have a .travis.yml.)

**Comment by jugmac00** [comment]
> Do we have cron builds enabled for this repo? (Ideally we'd run a script and enable them for all repos that have a .travis.yml.)

I just added one. Sometimes I have access to these settings, sometimes I don't ...
